// ============================================================================
// 自訂卡牌：在這裡新增原創卡牌，不需要重新產生資料就會出現在遊戲中。
// 效果使用與官方卡相同的 DSL（見 src/engine/types.ts）。
// 設 collectible: true 就會出現在卡包與收藏中。
//
// 範例（取消註解即可使用）：
// {
//   id: 'CUSTOM_001',
//   dbfId: 9000001,
//   name: '見習冒險者',
//   nameEn: 'Apprentice Adventurer',
//   text: '<b>戰吼：</b>抽一張牌',
//   type: 'MINION',
//   cardClass: 'NEUTRAL',
//   rarity: 'COMMON',
//   set: 9999,
//   cost: 2,
//   attack: 2,
//   health: 2,
//   collectible: true,
//   abilities: [{ on: { k: 'play' }, effects: [{ e: 'draw', count: 1, who: 'self' }] }],
// },
// ============================================================================
import type { CardDef } from '../engine/types';

export const CUSTOM_CARDS: CardDef[] = [
  {
    id: 'VH_SHAM_TRIAL',
    dbfId: 99004050,
    name: '自訂假審判',
    nameEn: 'Custom Sham Trial',
    text: '執行你為卡札克斯選擇的兩個審判效果。',
    type: 'SPELL',
    cardClass: 'WARLOCK',
    rarity: 'FREE',
    set: 9999,
    cost: 7,
    collectible: false,
    abilities: [{ on: { k: 'play' }, effects: [{ e: 'custom', fn: 'resolveShamTrial' }] }],
  },
  ...[
    ['VH_TRIAL_TYRANNY', '暴政補藥', 'Tonic of Tyranny', '召喚一個虛無領主。'],
    ['VH_TRIAL_SUGGEST', '暗示烈酒', 'Swill of Suggestibility', '為你的英雄恢復12點生命值。'],
    ['VH_TRIAL_CRATE', '違禁品箱', 'Crate of Contraband', '抽3張牌。'],
    ['VH_TRIAL_PERJURY', '偽證藥水', 'Potion of Perjury', '使你手中的手下消耗減少(2)。'],
    ['VH_TRIAL_CONTRACT', '犯罪契約', 'Criminal Contract', '召喚三個隨機3費手下。'],
    ['VH_TRIAL_SHIV', '偽造短刃', 'Spurious Shiv', '賦予你手中與場上的手下+3/+3。'],
    ['VH_TRIAL_CONSPIRACY', '共謀定罪', 'Convicted for Conspiracy', '控制一個隨機敵方手下。'],
    ['VH_TRIAL_SMUGGLING', '走私判刑', 'Sentenced for Smuggling', '從對手手中偷取2張牌。'],
    ['VH_TRIAL_DESTRUCTION', '毀滅拘留', 'Detained for Destruction', '強迫每個手下攻擊另一個手下。'],
    ['VH_TRIAL_RUSHED', '快速審判', 'Rushed Trial', '7費：審判立即結束。'],
    ['VH_TRIAL_GRUELING', '艱苦審判', 'Grueling Trial', '4費：在你的下個回合開始時結束。'],
    ['VH_TRIAL_UNENDING', '無盡審判', 'Unending Trial', '0費：4回合後結束。'],
  ].map(([id, name, nameEn, text], i): CardDef => ({
    id,
    dbfId: 99004100 + i,
    name,
    nameEn,
    text,
    type: 'SPELL',
    cardClass: 'WARLOCK',
    rarity: 'FREE',
    set: 9999,
    cost: 0,
    collectible: false,
  })),
  {
    id: 'VH_SKELETON_REFRESH',
    dbfId: 9900319,
    name: '刷新選項',
    nameEn: 'Refresh Options',
    text: '重新刷新發現選項。每次刷新有 20% 機率受到 5 點傷害。',
    type: 'SPELL',
    cardClass: 'MAGE',
    rarity: 'FREE',
    set: 9999,
    cost: 0,
    collectible: false,
  },
  {
    id: 'VH_ECTOPLASM',
    dbfId: 9900805,
    name: '靈質',
    nameEn: 'Ectoplasm',
    text: '重新召喚被《Slime \'em!》消滅的手下。',
    type: 'SPELL',
    cardClass: 'PRIEST',
    rarity: 'FREE',
    set: 9999,
    cost: 3,
    collectible: false,
    abilities: [{ on: { k: 'play' }, effects: [{ e: 'custom', fn: 'ectoplasm' }] }],
  },
];
