import type { Ability, CardDef, Effect, TargetReq } from '../engine/types';

type VioletOverride = Partial<
  Omit<CardDef, 'id' | 'dbfId' | 'name' | 'nameEn' | 'text' | 'type' | 'cardClass' | 'rarity' | 'set' | 'cost' | 'collectible'>
> & { tokens?: string[] };

const v = (id: string, args: Record<string, unknown> = {}): Effect => ({
  e: 'custom',
  fn: 'violet',
  args: { id, ...args },
});
const ab = (id: string, on: Ability['on'] = { k: 'play' }, args: Record<string, unknown> = {}, cond?: Ability['cond']): Ability => ({
  on,
  effects: [v(id, args)],
  ...(cond ? { cond } : {}),
});
const play = (id: string, args: Record<string, unknown> = {}): Ability[] => [ab(id, { k: 'play' }, args)];
const death = (id: string, args: Record<string, unknown> = {}): Ability[] => [ab(id, { k: 'deathrattle' }, args)];
const start = (id: string, args: Record<string, unknown> = {}): Ability[] => [ab(id, { k: 'startGame' }, args)];
const target = (filter: TargetReq['filter'], optional = false): TargetReq => ({ filter, ...(optional ? { optional: true } : {}) });

/**
 * 《紫羅蘭堡大逃亡》需要手動定義的卡。
 * 一般效果仍由共用 DSL 執行；會改變遊戲規則、牌庫/手牌控制或 Follow 的卡，
 * 統一交給 game.ts 的 violet dispatcher。
 */
export const VIOLET_OVERRIDES: Record<string, VioletOverride> = {
  // ---------------------------------------------------------------- Rogue / Wanted
  CAP_000: { abilities: [ab('CAP_000', { k: 'attack', subject: 'friendlyMinion' })] },
  CAP_001: { abilities: play('CAP_001'), target: target({ type: 'minion', side: 'any' }) },
  CAP_002: { abilities: play('CAP_002') },
  CAP_005: { abilities: [ab('CAP_005', { k: 'attack', subject: 'friendlyMinion' })] },
  CAP_006: { abilities: play('CAP_006'), target: target({ type: 'character', side: 'any' }) },
  CAP_101: { abilities: play('CAP_101') },
  CAP_103: { abilities: [ab('CAP_103', { k: 'attack', subject: 'friendlyHero', after: true })] },
  CAP_104: { abilities: [] },
  CAP_106: { abilities: play('CAP_106'), tokens: ['CAP_107t'] },
  CAP_107: { abilities: play('CAP_107'), tokens: ['CAP_107t'] },

  // ---------------------------------------------------------------- Warlock / Imp-formant
  CAP_400: { abilities: death('CAP_400'), tokens: ['CAP_400t2t'] },
  CAP_401: { abilities: play('CAP_401'), tokens: ['CAP_400t2t'] },
  CAP_402: { abilities: play('CAP_402'), tokens: ['CAP_400t2t'] },
  CAP_403: { abilities: play('CAP_403') },
  CAP_404: { abilities: play('CAP_404'), tokens: ['CAP_400t2t'] },
  CAP_405: {
    abilities: play('CAP_405'),
    tokens: ['CAP_405t1','CAP_405t2','CAP_405t3','CAP_405t4','CAP_405t5','CAP_405t6','CAP_405t7','CAP_405t8','CAP_405t9'],
  },
  CAP_406: { abilities: play('CAP_406'), tokens: ['CAP_400t2t'] },
  CAP_407: { abilities: play('CAP_407') },

  // ---------------------------------------------------------------- Priest / Reborn
  CAP_800: { abilities: [] },
  CAP_802: { abilities: play('CAP_802'), tokens: ['CAP_802t'] },
  CAP_803: { abilities: death('CAP_803') },
  CAP_804: { abilities: play('CAP_804'), target: target({ type: 'minion', side: 'friendly' }, true) },
  CAP_805: { abilities: play('CAP_805'), tokens: ['CAP_805t'] },
  CAP_806: { abilities: play('CAP_806') },

  // ---------------------------------------------------------------- Main set
  JAIL_029: { abilities: [ab('JAIL_029', { k: 'damaged', subject: 'friendlyMinion' }, {}, { c: 'itAlive' })] },
  JAIL_030: { abilities: [ab('JAIL_030', { k: 'attack', subject: 'self', after: true })] },
  JAIL_035: { abilities: play('JAIL_035') },
  JAIL_101: { abilities: play('JAIL_101'), target: target({ type: 'minion', side: 'enemy' }, true) },
  JAIL_118: { abilities: play('JAIL_118') },
  JAIL_122: { abilities: play('JAIL_122') },
  JAIL_123: { abilities: play('JAIL_123') },
  JAIL_200: { abilities: play('JAIL_200') },
  JAIL_202: { abilities: [] },
  JAIL_204: { abilities: [] },
  JAIL_205: { abilities: [ab('JAIL_205', { k: 'turnEnd', whose: 'mine' })] },
  JAIL_206: { abilities: play('JAIL_206') },
  JAIL_225: { abilities: play('JAIL_225'), target: target({ type: 'minion', side: 'any' }) },
  JAIL_303: { abilities: [...play('JAIL_303'), ...death('JAIL_303')] },
  JAIL_307: { abilities: play('JAIL_307') },
  JAIL_311: { abilities: [] },
  JAIL_313: { abilities: play('JAIL_313') },
  JAIL_319: { abilities: play('JAIL_319') },
  JAIL_321: { abilities: play('JAIL_321') },
  JAIL_326: { abilities: play('JAIL_326'), target: target({ type: 'minion', side: 'friendly' }) },
  JAIL_327: { abilities: play('JAIL_327') },
  JAIL_328: { abilities: death('JAIL_328') },
  JAIL_329: { abilities: [ab('JAIL_329', { k: 'attack', subject: 'friendlyHero', after: true })] },
  JAIL_330: { abilities: [] },
  JAIL_376: { abilities: death('JAIL_376') },
  JAIL_377: { abilities: play('JAIL_377') },
  JAIL_379: { abilities: play('JAIL_379') },
  JAIL_380: { abilities: death('JAIL_380') },
  JAIL_384: { abilities: start('JAIL_384') },
  JAIL_386: { abilities: play('JAIL_386'), tokens: ['JAIL_386t'] },
  JAIL_387: { abilities: play('JAIL_387') },
  JAIL_395: { abilities: play('JAIL_395'), target: target({ type: 'minion', side: 'friendly' }, true) },
  JAIL_397: { abilities: start('JAIL_397') },
  JAIL_398: { abilities: death('JAIL_398') },
  JAIL_399: { abilities: death('JAIL_399'), tokens: ['JAIL_399t1'] },
  JAIL_421: { abilities: [] },
  JAIL_430: { abilities: [...start('JAIL_430'), ...play('JAIL_430')] },
  JAIL_432: { abilities: play('JAIL_432') },
  JAIL_433: { abilities: play('JAIL_433'), target: target({ type: 'minion', side: 'any' }) },
  JAIL_434: { abilities: death('JAIL_434') },
  JAIL_435: { abilities: play('JAIL_435') },
  JAIL_436: { abilities: play('JAIL_436'), tokens: ['JAIL_436t','JAIL_436t2'] },
  JAIL_442: { abilities: death('JAIL_442'), tokens: ['JAIL_443t'] },
  JAIL_443: { abilities: [] , tokens: ['JAIL_443t'] },
  JAIL_444: { abilities: play('JAIL_444') },
  JAIL_446: { abilities: play('JAIL_446') },
  JAIL_447: { abilities: death('JAIL_447'), tokens: ['JAIL_447t'] },
  JAIL_448: { abilities: death('JAIL_448') },
  JAIL_452: { abilities: play('JAIL_452') },
  JAIL_453: { abilities: [] },
  JAIL_456: { abilities: play('JAIL_456') },
  JAIL_458: { abilities: [...play('JAIL_458'), ab('JAIL_458', { k: 'attack', subject: 'friendlyHero', after: true }, { repeat: true })], tokens: ['JAIL_458t1','JAIL_458t2','JAIL_458t3','JAIL_458t4'] },
  JAIL_459: { abilities: [], keywords: ['RUSH','POISONOUS'], auras: [{ scope: 'otherFriendly', keywords: ['POISONOUS'] }] },
  JAIL_461: { abilities: play('JAIL_461') },
  JAIL_462: { abilities: play('JAIL_462') },
  JAIL_470: { abilities: play('JAIL_470') },
  JAIL_474: { abilities: play('JAIL_474') },
  JAIL_500: { abilities: play('JAIL_500') },
  JAIL_501: { abilities: play('JAIL_501'), target: target({ type: 'minion', side: 'enemy' }, true) },
  JAIL_502: { abilities: [ab('JAIL_502', { k: 'turnStart', whose: 'mine' })] },
  JAIL_503: { abilities: death('JAIL_503') },
  JAIL_504: { abilities: play('JAIL_504'), tokens: ['JAIL_504t','JAIL_504t2','JAIL_504t3'] },
  JAIL_507: { abilities: play('JAIL_507') },
  JAIL_509: { abilities: start('JAIL_509') },
  JAIL_510: { abilities: play('JAIL_510') },
  JAIL_515: { abilities: play('JAIL_515'), target: target({ type: 'minion', side: 'enemy' }) },
  JAIL_516: { abilities: play('JAIL_516') },
  JAIL_703: { abilities: death('JAIL_703') },
  JAIL_706: { abilities: play('JAIL_706') },
  JAIL_719: { abilities: play('JAIL_719') },
  JAIL_721: { abilities: [ab('JAIL_721', { k: 'summon', side: 'friendly', race: 'DEMON' })] },
  JAIL_730: { abilities: [ab('JAIL_730', { k: 'attack', subject: 'friendlyHero', after: true })] },
  JAIL_732: { abilities: play('JAIL_732') },
  JAIL_733: { abilities: death('JAIL_733') },
  JAIL_734: { abilities: play('JAIL_734') },
  JAIL_735: { abilities: play('JAIL_735') },
  JAIL_800: { abilities: start('JAIL_800') },
  JAIL_801: { abilities: play('JAIL_801'), tokens: ['JAIL_801t'] },
  JAIL_802: { abilities: [ab('JAIL_802', { k: 'cardPlayed', side: 'friendly', cardType: 'MINION' })] },
  JAIL_803: { abilities: play('JAIL_803'), target: target({ type: 'character', side: 'enemy' }), tokens: ['JAIL_803t'] },
  JAIL_805: { abilities: play('JAIL_805'), tokens: ['JAIL_805t'] },
  JAIL_806: { abilities: play('JAIL_806') },
  JAIL_831: { abilities: play('JAIL_831') },
  JAIL_850: { abilities: [ab('JAIL_850', { k: 'cardPlayed', side: 'friendly', cardType: 'MINION' })] },
  JAIL_851: { abilities: play('JAIL_851') },
  JAIL_852: { abilities: play('JAIL_852') },
  JAIL_860: { abilities: start('JAIL_860') },
  JAIL_861: { abilities: play('JAIL_861') },
  JAIL_866: { abilities: play('JAIL_866') },
  JAIL_875: { abilities: [ab('JAIL_875', { k: 'attack', subject: 'friendlyHero', after: true })] },
  JAIL_876: { abilities: play('JAIL_876'), target: target({ type: 'minion', side: 'friendly' }) },
  JAIL_879: { abilities: play('JAIL_879'), tokens: ['JAIL_879t'] },
  JAIL_880: { abilities: [ab('JAIL_880', { k: 'cardPlayed', side: 'friendly', cardType: 'MINION' })] },
  JAIL_881: { abilities: play('JAIL_881'), tokens: ['JAIL_881t'] },
  JAIL_882: { abilities: [...play('JAIL_882'), ...death('JAIL_882')] },
  JAIL_890: { abilities: [] },
  JAIL_891: { abilities: play('JAIL_891'), target: target({ type: 'minion', side: 'any' }) },
  JAIL_892: { abilities: play('JAIL_892'), target: target({ type: 'character', side: 'any' }) },
  JAIL_906: { abilities: death('JAIL_906') },
  JAIL_909: { abilities: [ab('JAIL_909', { k: 'play' }, {}, { c: 'combo' })] },
  JAIL_940: { abilities: play('JAIL_940') },
  JAIL_941: { abilities: play('JAIL_941'), target: target({ type: 'character', side: 'any' }), tokens: ['JAIL_941t'] },
  JAIL_974: { abilities: death('JAIL_974') },
  JAIL_986: { abilities: play('JAIL_986') },
  JAIL_997: { abilities: play('JAIL_997'), target: target({ type: 'minion', side: 'any' }) },
};
